# Generated by Django 3.2.4 on 2021-06-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='change',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
