# Generated by Django 2.0 on 2021-09-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0002_line_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField()),
                ('name1', models.TextField(null=True)),
                ('text1', models.TextField(null=True)),
                ('name2', models.TextField(null=True)),
                ('text2', models.TextField(null=True)),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
