# Generated by Django 2.0 on 2021-09-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0003_auto_20210903_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_bert', models.TextField(null=True)),
                ('fenzhen', models.BooleanField()),
                ('history', models.TextField(null=True)),
                ('ks', models.TextField(null=True)),
                ('entity', models.TextField(null=True)),
                ('docker_name', models.TextField(null=True)),
                ('docker_num', models.TextField(null=True)),
            ],
        ),
    ]
