# Generated by Django 2.0.1 on 2021-11-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0004_sess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField()),
                ('ip', models.TextField(null=True)),
                ('fenzhen', models.TextField(null=True)),
                ('dialogue', models.TextField(null=True)),
                ('entity', models.TextField(null=True)),
                ('record', models.TextField(null=True)),
                ('moblie', models.BooleanField()),
                ('User_Agent', models.TextField(null=True)),
                ('evaluation', models.TextField(null=True)),
            ],
        ),
    ]
