# Generated by Django 2.0.1 on 2021-12-16 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0005_dialogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='times',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
